her/config/routes.rb
Rails.application.routes.draw do
  get 'article_form/index'
  get 'article/index'
  resources :request_executions
  get 'request_execution/index'
  get 'request/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'get_article/:id' , to: 'get_article#show'
end

her/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

her/app/models/art.rb
class Art
  include Her::Model
end

her/app/models/request.rb
class Request < ApplicationRecord
end

her/app/models/request_execution.rb
class RequestExecution < ApplicationRecord
  has_one_attached :image
end

her/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

her/app/controllers/article_form_controller.rb
class ArticleFormController < ApplicationController
  def index
  end
end

her/app/controllers/get_article_controller.rb
class GetArticleController < ApplicationController
  def show
    pp "****************************"
    pp params
    id=params.permit(:id,:title,:text)
    pp params
    #pp Art.all.fetch
    pp Art.find(1)
    render json: {test:"OK"} #Art.find(params[:id])
  end


end

her/app/controllers/request_controller.rb
class RequestController < ApplicationController
  def index
  end
end

her/app/controllers/request_executions_controller.rb
class RequestExecutionsController < ApplicationController
  def new
    @request_exceution = RequestExecution.new
  end

  def create
    pp "*******************************"
    pp params
    @request_execution = RequestExecution.create params.permit(:content, :image) # POINT
    redirect_to @request_execution
  end

  def show
    @request_execution = RequestExecution.find(params[:id])
  end
end

her/app/helpers/application_helper.rb
module ApplicationHelper
end

her/app/helpers/article_form_helper.rb
module ArticleFormHelper
end

her/app/helpers/request_executions_helper.rb
module RequestExecutionsHelper
end

her/app/helpers/request_helper.rb
module RequestHelper
end

her/app/views/article_form/index.html.erb
<%= react_component("Article", {}) %>

her/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smith</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'hello_react' %>   

  </head>

  <body>
    <%= yield %>
  </body>
</html>

her/app/views/request/index.html.erb
<h1>Request#index</h1>
<p>Find me in app/views/request/index.html.erb</p>

her/app/views/request_executions/new.html.erb
<%= form_with model: @request_execution, url: request_executions_path, local: true  do |form| %>
  <%= form.text_area :content %><br>
  <%= form.file_field :image %><br>
  <%= form.submit %>
<% end %>

her/app/views/request_executions/show.html.erb
content: <%= @request_execution.content %>
<br />
<% if @request_execution.image.attached? %>
  <%= image_tag @request_execution.image %>
<% end %>