srv/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  resources :arts
end

srv/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

srv/app/models/article.rb
class Article < ApplicationRecord
end

srv/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

srv/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end
  def create
    @article = Article.new(article_params)

    @article.save
    redirect_to @article
  end
  def show
    @article = Article.find(params[:id])
  end
  def index
    @articles = Article.all
  end

end

private

def article_params
  params.require(:article).permit(:title, :text)
end

srv/app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    @art = Article.new(art_params)
    pp @art
    if @art.save 
      render json: {status: "OK", data: @art} 
    else
      render json: {status: error, data: @art.errors}
    end
  end
  def show
    render json: Article.find(params[:id])
  end
  def index
    render json: Article.all
  end
  def update
    @art = Article.find(params[:id])
    if params[:text].present?
      @art.update(text: params[:text])
    end
    if params[:title].present?
      @art.update(title: params[:title])
    end
    if @art.save 
      render json: {status: "OK", data: @art} 
    else
      render json: {status: "error", data: @art.errors}
    end
  end
end

private

def art_params
  a=params.permit(:title, :text)
end

srv/app/helpers/application_helper.rb
module ApplicationHelper
end

srv/app/helpers/articles_helper.rb
module ArticlesHelper
end

srv/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

srv/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

srv/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

srv/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smith</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>